### ISSUE TITLE
wrong geometric error

### ISSUE THREAD

**Issue by bertt** [Geodan/i3dm.export#23]
When running i3dm.export, root geometricError = 0 is generated

```
  "geometricError": 0.0,
  "asset": {
    "generator": "i3dm.export",
    "version": "1.0"
  } 
```

This should be another value (for example 1000)

**Comment by bertt** [comment]
fix: Removed root tilesetJson.GeometricError 

https://github.com/Geodan/i3dm.export/commit/135a1d8040082bf9d4255031b930e8ab877a4c02

todo: test with supertileset, mapbox

**Comment by bertt** [comment]
tested with MapBox viewer: there is nothing drawn after creating a tileset with this fix.

1] Before fix:

https://bertt.github.io/mapbox_3dtiles_samples/samples/instanced_bug/works/#16.37/52.366463/4.8959/0/45

![image](https://user-images.githubusercontent.com/538812/134519739-51ac0dc2-2378-4e63-a24d-43d37672b534.png)

2] After fix:

https://bertt.github.io/mapbox_3dtiles_samples/samples/instanced_bug/error/#16.37/52.366463/4.8959/0/45

![image](https://user-images.githubusercontent.com/538812/134519662-ef0990fa-abfe-48a8-bc88-2ed518a5f864.png)

The only change is GeometricError is removed from root (Cesium does not use this):

From:

```
  "geometricError": 500.0,
  "asset": {
    "generator": "i3dm.export",
    "version": "1.0"
  }
```

to:

```
  "asset": {
    "generator": "i3dm.export",
    "version": "1.0"
  }
```

Question: Apparently Mapbox-3d-tiles client uses root.GeometricError, can we remove this?

cc @tebben

**Comment by tebben** [comment]
Ok, I will have a look at this somewhere this week

**Comment by bertt** [comment]
wrong solution here, it should be possible to add geometricError at root level, for example see

https://github.com/CesiumGS/3d-tiles/blob/main/specification/README.md#tileset-json

**Comment by bertt** [comment]
reverted this change.  At root level there is now geometricError[0[] defined.

```
 "geometricError": 500.0,
  "asset": {
    "generator": "i3dm.export",
    "version": "1.0"
  }
```
