### ISSUE TITLE
Why can't Installation succeed on i3dm.export?

### ISSUE THREAD

**Issue by qwork2010** [Geodan/i3dm.export#70]
@bertt 
Hello !
On the path“ [https://github.com/Geodan/i3dm.export ](https://github.com/Geodan/i3dm.export)”I downloaded the program.

![1b](https://github.com/user-attachments/assets/2875e3c0-6600-449e-abab-0e6ea3327366)

1] Use pre-built binaries from release

![1](https://github.com/user-attachments/assets/d7458a37-9047-463a-8b69-1c59b933391a)

Run the program i3dm.xport.exe, the software crashes.

2] Use . NET Tool
Prerequisite: .NET 8.0 SDK is installed https://dotnet.microsoft.com/download/dotnet/8.0
use. NET tool, the result information shows an error.

![2](https://github.com/user-attachments/assets/a091a0d5-4b5a-47ea-867d-fb266fed77b9)
![3](https://github.com/user-attachments/assets/f37eeb9b-9480-4129-bd38-d3dc52fa096d)
![4](https://github.com/user-attachments/assets/53135eb0-f270-4ae3-b095-040d723d961f)

May I ask how to solve this problem?

**Comment by bertt** [comment]
Method 1] Use pre-built binaries from release

Did you run from command line? What error did you get?

Method 2] Use . NET Tool

Error indicates database is not running (or accessible) on 127.0.0.1:5432

**Comment by qwork2010** [comment]
@bertt 
Method 1] Use pre-built binaries from release
Thank you for your answer!
I did not run it through the command line, it was run by double clicking.
After double clicking, the program crashes. As shown in the figure below.
![GIF 2024-9-24 11-32-58](https://github.com/user-attachments/assets/134b99d4-9418-46ff-b4d7-3065ca4284fd)

**Comment by qwork2010** [comment]
@bertt 
@bertt
Method 1] Use pre-built binaries from release
Thank you for your answer!
I did not run it through the command line, it was run by double clicking.
After double clicking, the program crashes. As shown in the figure below.
![GIF 2024-9-24 11-39-05](https://github.com/user-attachments/assets/ed7361f3-c59a-44d0-bcfb-7991e9a7feb6)

**Comment by bertt** [comment]
use the commandline no doubleclick

![image](https://github.com/user-attachments/assets/69b9945c-dc76-4a8a-9c6a-c241e2144290)
