### ISSUE TITLE
i3dm.export launched in Docker fails to connect to postgres 

### ISSUE THREAD

**Issue by chekhovana** [Geodan/i3dm.export#71]
Hello,

I am trying to reproduce the steps described in [getting started](https://github.com/Geodan/i3dm.export/blob/main/docs/getting_started.md).

I can ensure that Postgres database is up and running by connecting to it from python script. But the following command:
```
docker run --platform linux/amd64 -it -v $(pwd)/output:/app/output -v $(pwd)/glb:/glb geodan/i3dm.export \
  -c "Host=localhost;Username=postgres;Password=postgres;Database=postgres;Port=5432" \
  -t traffic_signs_instances
```
raises exception:
```
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Failed to connect to 127.0.0.1:5432
```

Is there any way to fix it? Thanks in advance.

Environment:
OS: macOS Sonoma 14.5
Docker: 27.1.1

**Comment by bertt** [comment]
Do not use localhost, but the name of the machine Postgres is running on. Also when Postgres is running in Docker too, the 2 docker containers must be in the same network to be able to make a connection

**Comment by chekhovana** [comment]
@bertt thanks for the advice, I'll try to implement what you said. 

Installed i3dm.export tool works fine.

**Comment by chekhovana** [comment]
@bertt 
Noteworthy, if I remove volume mounting `./glb:/app`, then the tool starts, but then exits with FileNotFoundException:
```
Attaching to test_i3dm-i3dm
test_i3dm-i3dm  | Tool: I3dm.export
test_i3dm-i3dm  | Version: 2.8.3.0
test_i3dm-i3dm  | Exporting instances from traffic_signs_instances...
test_i3dm-i3dm  | Use GPU instancing: False
test_i3dm-i3dm  | Bounding box for table (WGS84): 4.735, 52.2634, 5.0264, 52.4468
test_i3dm-i3dm  | Vertical for table (meters): 0, 10
test_i3dm-i3dm  | Spatial reference of traffic_signs_instances.geom: 4326
test_i3dm-i3dm  | Maximum instances per tile: 1000
test_i3dm-i3dm  | Start generating tiles...
test_i3dm-i3dm  | Unhandled exception. System.IO.FileNotFoundException: Could not find file '/app/Box.glb'.
test_i3dm-i3dm  | File name: '/app/Box.glb'
```

**Comment by bertt** [comment]
Maybe the line

```
    command: i3dm.export -c "Host=database;Username=postgres;Password=postgres;Database=postgres;Port=5432" -t traffic_signs_instances
```

Should be

```
    command: -c "Host=database;Username=postgres;Password=postgres;Database=postgres;Port=5432" -t traffic_signs_instances
```

Because the command runs on startup

```
docker run geodan/i3dm.export
````

**Comment by chekhovana** [comment]
No, errors remains the same

**Comment by chekhovana** [comment]
@bertt thank you, but I'd prefer to avold urls, plain files are preferable in my case. What do you mean by `correct` folder? According to the error message:

`Unhandled exception. System.IO.FileNotFoundException: Could not find file '/app/Box.glb'`

- the `Box.glb` should be the placed in the`/app` folder

Is it possible to change the code so that the glb-models would be searched not in the `/app` folder, but in the `/glb` folder?

**Comment by bertt** [comment]
when running in a container, /app is the working directory. 

In the getting started there is no path defined for box.glb, so the tool i3dm.export will search for the model in the /app folder:

```
postgres=# CREATE TABLE traffic_signs_instances as (
	SELECT ogc_fid as id, 
	st_transform(wkb_geometry, 4326) as geom,
	1 +  random() as scale,
	random()*360 as rotation,
	'Box.glb' as model,
	json_build_array(json_build_object('id',ogc_fid), json_build_object('bevestiging',bevestiging)) as tags
	from traffic_signs
);
```

When you placed the models in another directory (like 'glb') - suing a mount or not, you can also define it like this in the input table:

```
postgres=# CREATE TABLE traffic_signs_instances as (
	SELECT ogc_fid as id, 
	st_transform(wkb_geometry, 4326) as geom,
	1 +  random() as scale,
	random()*360 as rotation,
	'/glb/Box.glb' as model,
	json_build_array(json_build_object('id',ogc_fid), json_build_object('bevestiging',bevestiging)) as tags
	from traffic_signs
);
```

**Comment by chekhovana** [comment]
Ok, now I got it. Thank you very much for your help!
