### ISSUE TITLE
Poor rendering performance with large model

### ISSUE THREAD

**Issue by chekhovana** [Geodan/i3dm.export#72]
Hello, @bertt 

I created sample tileset with 90 instances and added it to my Unreal project with Cesium plugin. When I use Box.glb as model, everything works. But when I replace Box.blg with larger model of tree sized approximately to 120 Mb ([jacaranda.glb](https://drive.google.com/file/d/1gvTRnLg825YB1PYbDRzYd_0vYMRRYjmc/view?usp=drive_link)), then Unreal almost hangs, rendering is very slow. Is there any way to improve performance? Are there any model size limitations?

Thanks in advance.

**Comment by bertt** [comment]
Hi, 120MB for a model sounds big for me, is there a way to reduce it's size? Or look at (Draco) compression options.
Better place to discuss this is https://community.cesium.com/ in the Unreal section.

**Comment by chekhovana** [comment]
@bertt thanks for the answer!
