### ISSUE TITLE
The folder contains multiple glb files, how convert to tileset.json?

### ISSUE THREAD

**Issue by DimplesHei** [Geodan/i3dm.export#83]
The folder contains multiple glb files, how convert to tileset.json?

**Comment by bertt** [comment]
So as  I understand you have a set of glb files, and want to create 3D Tileset out of it? Do you know the locations of the glb's?

If so, one option is to fill a input table with model = {name of glb model}, geom = {position of the model} and the rest of the needed columns. Then run i3dm.export with --max_features_per_tile = 1 (so every glb will have 1 instance) and a tileset will be created.

Another option if the set of glb's is not large: write some code to create tileset.json with references to the glb files.

**Comment by DimplesHei** [comment]
thanks

**Comment by bertt** [comment]
see also https://bertt.wordpress.com/2022/02/20/cesium-3d-tiles-model-placement/ for creating tileset.json referencing a glTF model
